name: Trigger Dmainking Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger DirectAdmin Git Pull
        run: |
          curl -X POST "https://host-ww.net" \
          -u "emmarodg:${{ secrets.DA_PASSWORD }}" \
          -H "Content-Type: application/json" \
          -d '{}'
