name: Production Live Deployment

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Latest Code Base
        uses: actions/checkout@v4

      - name: Set Up Node Engine
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Download Modules
        run: npm ci

      - name: Compile NextJS Static Output
        run: npm run build

      - name: Install Secure FTP Client Tools
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Directly Stream Code Using Linux Engine
        run: |
          lftp -e "set ftp:ssl-allow no; open ftp://da16.host-ww.net; user '${{ secrets.FTP_USERNAME }}' '${{ secrets.FTP_PASSWORD }}'; mirror -R ./out/ ./domains/://emmarodgerspomeranian.com; quit"
